### ISSUE TITLE
Error while running the main script

### ISSUE THREAD

**Issue by FShinoda** [pythonarcade/performance_tests#1]
Hello there! I gladly found this performance test repo, it will help me a lot. Thanks for that!

I didn't add nothing to the repo, just followed the README instructions:
I am getting the error below when I run the main script, though... 
Could you help me? I am new to those game engines and I don't know how to solve that. Tried some search, but got nothing...

<img width="524" alt="image" src="https://github.com/pythonarcade/performance_tests/assets/45886482/c39c00e8-6cf3-4b9c-b87f-93fda111a63d">

Thanks in advance!

**Comment by pvcraven** [comment]
Hm, I've only been testing it with the 3.0 beta. You might try installing that. It is a pre release. If you aren't familiar with installing pre-releases on pypi give me a shout.

**Comment by FShinoda** [comment]
Oh, I am not! could you show me how to do it?

**Comment by pvcraven** [comment]
If you go to pypi for arcade:
https://pypi.org/project/arcade/#history
You can see the latest pre-release version is 3.0.0.dev21


That can be installed with "pip install arcade==3.0.0.dev21"

What are you using for a development environment? Are you using a venv (virtual environment)?

I'm on the road for a few more days so I can't give detailed answers as I have no computer in front of me.

**Comment by FShinoda** [comment]
Oh, it worked for the initial error! I started using venv and it solved the problem.

Still, I am getting some errors... 
When It is running the moving arcade sprites it crashes and outputs the following error:

> Traceback (most recent call last):
>   File "C:\Users\User\OneDrive\Área de Trabalho\repos\performance_tests\src\__main__.py", line 29, in <module>
>     arcade_tests.draw_moving_sprites.main()
>   File "C:\Users\User\OneDrive\Área de Trabalho\repos\performance_tests\src\arcade_tests\draw_moving_sprites.py", line 140, in 
> main
>     arcade.run()
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\arcade\window_commands.py", line 238, in run   
>     pyglet.app.run(window._draw_rate)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\app\__init__.py", line 76, in run       
>     event_loop.run(interval)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\app\base.py", line 151, in run
>     timeout = self.idle()
>               ^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\app\base.py", line 212, in idle
>     self.clock.call_scheduled_functions(dt)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\clock.py", line 227, in call_scheduled_functions
>     item.func(now - item.last_ts, *item.args, **item.kwargs)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\app\base.py", line 118, in _redraw_windows
>     window.dispatch_event('on_draw')
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\window\__init__.py", line 668, in dispatch_event
>     super().dispatch_event(*args)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyglet\event.py", line 387, in dispatch_event  
>     if getattr(self, event_type)(*args):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\OneDrive\Área de Trabalho\repos\performance_tests\src\arcade_tests\draw_moving_sprites.py", line 95, in on_draw
>     arcade.start_render()
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\arcade\window_commands.py", line 256, in start_render
>     get_window().clear()
>     ^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\arcade\window_commands.py", line 64, in get_window
>     raise RuntimeError(
> RuntimeError: No window is active. It has not been created yet, or it was closed.

I did not closed the window or something like this.
Can you help me?
